menu:
  Home: /
  Archives: /archives

widgets:
- search

cover:
  enable: true
  url: backgrounds/pegazy.jpg
   
excerpt_link: Read More

full_format: 'ddd, MMM D YYYY, h:mm:ss a'

addthis:
  enable: true
  pubid:
  facebook:
  twitter:
  google: true
  pinterest:

fancybox: true

google_analytics: UA-368771XX-X
rss:

comment_provider: duoshuo

# Duoshuo comment
duoshuo:
  short_name: ravanave

social:
  github: https://github.com/jhirniak
  linkedin: http://linkedin.com/jaroslawhirniak
  google_plus: 

auto_change:
  enable: true
